name: flustora

env: 
  VSCOE_VERSION: "1.74.3"
  DART_VERSION: "2.x"
  DART_CHANNEL: "stable"
  FLUTTER_VERSION: "3.x"
  FLUTTER_CHANNEL: "stable"

on:
  push:
    branches:
      - "main"

jobs:
  flustora_testing:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: /packages/flustora/
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Checkout Flutter Actions
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          channel: ${{env.FLUTTER_CHANNEL}}
          
      - name: Flustora testing
        run: |
          flutter pub get
          flutter analyze
          flutter test

   